### ISSUE TITLE
ImportError: cannot import name 'HTTPClientFactory' from 'twisted.web.client' (unknown location)

### ISSUE THREAD

**Issue by bitailab** [s884812/openvpn_as_crack#7]
![image](https://github.com/user-attachments/assets/700bab9d-1030-42e0-818e-5aa0a447b889)
用的是pyovpn-2.0-py3.10.egg，openvpn 是 2.14 版本

**Comment by s884812** [comment]
你只能用倉庫裡的版本，不能用官方的新版。
